In [5]:
import numpy as np

In [6]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [7]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [8]:
type(arr1)

numpy.ndarray

nd = n-Dimensional

In [9]:
arr2 = np.arange(10, 20, 1) #(start, stop (non-inclusive), step-size)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
list1

[10, 20, 30]

In [11]:
list2 = [40, 50, 60]

In [14]:
list3 = [list1, list2]
list3

[[10, 20, 30], [40, 50, 60]]

In [15]:
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [16]:
arr3.shape

(2, 3)

In [17]:
arr3dim = np.array(
    [
        [
            [1, 2, 3], [3, 4, 5]
        ],
        [
            [5, 6, 7], [7, 8, 9]
        ]
    ]
)
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [18]:
arr3dim.shape

(2, 2, 3)

Matrix Operations

In [19]:
arr3dim *

SyntaxError: invalid syntax (1273300935.py, line 1)

In [20]:
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [21]:
arr1

array([10, 20, 30])

In [22]:
arr11 = np.array(list2)

In [23]:
arr11

array([40, 50, 60])

In [24]:
arr1.shape == arr11.shape

True

In [25]:
arr1 * arr11

array([ 400, 1000, 1800])

In [26]:
arr1 * arr3dim

array([[[ 10,  40,  90],
        [ 30,  80, 150]],

       [[ 50, 120, 210],
        [ 70, 160, 270]]])

# Lab
Create ndarrays of the following sizes:
1. One dimensional array with 12 elements(12,
2. Two dimensional array of size(3,4) (Column, Rows)
3. Three dimensional array of size (2,5,4)

In [29]:
arr111 = np.arange(1, 13, 1)
arr111

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
arr112 = np.array([[ 1,  2,  3,  4],  [5,  6,  7,  8],  [9, 10, 11, 12]])
arr112

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr113 = np.array(
    [
        [
            [1, 2, 3, 4], [5, 4, 5, 6], [6, 7, 8, 9], [9, 4, 6, 2], [8, 7, 8, 1]
        ],
        [
            [5, 6, 7, 7], [8, 9, 5, 4], [3, 2, 5, 7], [8, 7, 9, 1], [4, 5, 1, 2]
        ]
    ]
)
arr113

array([[[1, 2, 3, 4],
        [5, 4, 5, 6],
        [6, 7, 8, 9],
        [9, 4, 6, 2],
        [8, 7, 8, 1]],

       [[5, 6, 7, 7],
        [8, 9, 5, 4],
        [3, 2, 5, 7],
        [8, 7, 9, 1],
        [4, 5, 1, 2]]])

In [34]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [35]:
arr3[1][2]

60

In [36]:
arr3[0]

array([10, 20, 30])

In [38]:
arr3[:, 1]

array([20, 50])

In [39]:
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [40]:
arr3dim[:, :, 1]

array([[2, 4],
       [6, 8]])

In [42]:
arr3dim.sum()

60

In [43]:
arr3dim.std()

2.3804761428476167

In [44]:
arr3dim.mean()

5.0

In [45]:
arr3dim.mean(1)

array([[2., 3., 4.],
       [6., 7., 8.]])

In [47]:
arr3dim.mean(2)

array([[2., 4.],
       [6., 8.]])

In [48]:
arr3dim.var()

5.666666666666667

In [49]:
arr3dim.min()

1

In [50]:
arr3dim.max()

9

In [51]:
for x in arr1:
    print(x)

10
20
30


In [52]:
for dim in arr3:
    for x in dim:
        print(x)

10
20
30
40
50
60


In [53]:
for x in np.nditer(arr2):
    print(x)

10
11
12
13
14
15
16
17
18
19


In [54]:
np.save("new_array", arr3)

In [55]:
np.load("new_array.npy")

array([[10, 20, 30],
       [40, 50, 60]])

In [56]:
np.savetxt("new_array.txt", arr3, delimiter='\t')

In [57]:
np.loadtxt("new_array.txt", delimiter='\t', dtype=int)

array([[10, 20, 30],
       [40, 50, 60]])